### ISSUE TITLE
Weird artifact in bottom bar

### ISSUE THREAD

**Issue by atheistd** [erremauro/TwoDark#10]
Maybe the title isn't clear, so here is a [screencast](https://youtu.be/XUsjkRzB7AM).

```
$ subl --version
Sublime Text Build 4107
```

Removing the lines `"theme": "TwoDark.sublime-theme",` and `"color_scheme": "Packages/Theme - TwoDark/TwoDark.tmTheme",` from `~/.config/sublime-text-3/Packages/User/Preferences.sublime-settings` will remove the artifact. Adding them starts the artifact again. Also, with the theme enabled, going fullscreen will prevent the artifact to appear unless the user exits the fullscreen window.

**Comment by erremauro** [comment]
Hi, the theme has been updated to `sublime-color-scheme`. Just change the preferences to:

```json
{
  "theme": "TwoDark.sublime-theme",
  "color_scheme": "Packages/Theme - TwoDark/TwoDark.sublime-color-scheme",
  "draw_shadows": false,
  "highlight_modified_tabs": true,
  "caret_extra_width": 1,
  "caret_style": "smooth",
}
```

**Comment by atheistd** [comment]
This is my current config, and I still see the artifacts.

```
{
	"atomic_save": true,
	"auto_complete_delay": 1,
	"auto_complete_triggers":
	[
		{
			"characters": ".",
			"selector": "source.python",
		}
	],
	"caret_extra_width": 1,
	"caret_style": "smooth",
	"draw_shadows": false,
	"ensure_newline_at_eof_on_save": true,
	"fade_fold_buttons": true,
	"font_face": "Fira Code",
	"font_options":
	[
		"subpixel_antialias"
	],
	"font_size": 10,
	"highlight_modified_tabs": true,
	"ignored_packages":
	[
		"Vintage",
	],
	"indent_guide_options":
	[
		"draw_active"
	],
	"save_on_focus_lost": true,
	"shift_tab_unindent": true,
	"show_encoding": true,
	"show_line_endings": true,
	"theme": "TwoDark.sublime-theme",
	"color_scheme": "Packages/Theme - TwoDark/TwoDark.sublime-color-scheme",
}
```

**Comment by erremauro** [comment]
I submitted a new version (v1.2.3) that should resolve the issue. You should receive it in the following hours. Thanks for your input!

**Comment by atheistd** [comment]
Oh okay, thanks. I'll reply once I receive the v1.2.3 update. Thanks again for this excellent theme! :D

**Comment by atheistd** [comment]
I updated all the packages [including TwoDark to v1.2.3] and it appears that the issue is now resolved.

Never thought a simple fix in a theme would make me this happy, thanks again!
