### ISSUE TITLE
Scroll bars?

### ISSUE THREAD

**Issue by cesaraaron** [erremauro/TwoDark#3]
Don't show in any view/panel.
It's just to me or they're not supported in your theme?

**Comment by erremauro** [comment]
You are right, they're not supported at the moment. The Minimap is essentially a vertical scrollbar. However, I've decided to add them back since their behavior can be controlled in the settings anyway. I've planned to release an update in the following weeks.

Thanks for your feedback!

**Comment by erremauro** [comment]
[Version 1.1.0](https://github.com/erremauro/TwoDark/releases) add scrollbars support. If you installed the theme using packagecontrol, the update will be available as soon as they grab the new release from the repo.

**Comment by cesaraaron** [comment]
Oh thanks!

Just one thing more:
![sketch](https://cloud.githubusercontent.com/assets/20180899/21020979/44ea4cfc-bd3c-11e6-8979-e29e26545000.png)

**Comment by erremauro** [comment]
Hi, [TwoDark v1.1.1](https://github.com/erremauro/TwoDark/releases) update scrollbars background color and width to match OneDark for Atom.
