### ISSUE TITLE
ignored git folders

### ISSUE THREAD

**Issue by terencechow** [erremauro/TwoDark#4]
First off gotta say great job because i downloaded a bunch of themes and this comes closest to atom.

I just noticed the gitignored files/folders are not a slightly darker color like in atom. Can we have this or can you direct me on how to change this? I'll look into changing it / submitting a PR if you can provide me direction on this...Thanks!

**Comment by erremauro** [comment]
Hi and thanks for the kind words. It would be great, but given that Sublime Text doesn't integrate git out of the box like Atom does, there's no theme support for such feature. I don't know how Sublime Text plugin system works and if it could be implemented that way but I'll look into that.

Anyway, thanks for your feedback!
