### ISSUE TITLE
关于“&”问题(Questions about "&")

### ISSUE THREAD

**Issue by flc1125** [erremauro/TwoDark#5]
您的主题非常好用（Your theme is very nice!）,但是使用起来会有一个问题！（Yet there will be a problem for you to use!）

当输入`&`的时候，会导致看不清(When the input ` & `, will lead to can't see)；如图：（For example:）

![1](https://cloud.githubusercontent.com/assets/14297703/21471748/7e67d562-caf7-11e6-82d9-4f07461b184d.png)

![2](https://cloud.githubusercontent.com/assets/14297703/21471755/c5c50272-caf7-11e6-8add-c6759c6c04ae.png)

----

代码（code）：

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>
    你好！&
</body>
</html>
```

**Comment by erremauro** [comment]
I'm afraid this a parsing error on [one-dark-sublime-text-3-color-scheme](https://github.com/IceTimux/one-dark-sublime-text-3-color-scheme), a third party color scheme developed by [IceTimux](https://github.com/IceTimux) that is included in TwoDark.

I was planning so try to solve some of the issues the color scheme has. I'll see what I can do.

Thank you for your feeddback!
