### ISSUE TITLE
xml file has no icon

### ISSUE THREAD

**Issue by kumiao** [erremauro/TwoDark#6]
I find xml file has no icon, please fix it！

**Comment by erremauro** [comment]
Icons are defined by syntax extension definitions, not by the theme.

**Comment by kumiao** [comment]
but why default theme has icon, use your theme icon disappear！
![image](https://cloud.githubusercontent.com/assets/16172180/22508499/3b8229e6-e8c5-11e6-9132-f46ce2444a73.png)

default theme：
![image](https://cloud.githubusercontent.com/assets/16172180/22508530/5c57cf22-e8c5-11e6-987f-cfad3d9767e4.png)

**Comment by erremauro** [comment]
Apparently Sublime Text wasn't picking up the default icon override from theme preferences. I've added a generic markup icon to fix the issue.

[TwoDark v1.1.2](https://github.com/erremauro/TwoDark/releases/tag/1.1.2) should solve the problem.

Thanks a lot for the feedback!
