### ISSUE TITLE
Atom color for blade syntax

### ISSUE THREAD

**Issue by elvis-pereira** [erremauro/TwoDark#7]
First of all, thank you for the excellent work. I started to use Sublime a short time in the place of Atom and the only thing that I had been missing was the style of the Atom, but not anymore 😃

I have only one doubt, in Atom the blade syntax uses color #C678DD for @if for example, it was quite easy to see

![atom-blade](https://cloud.githubusercontent.com/assets/8865334/23878388/dddb1070-0825-11e7-8ee0-2c48ccac9dee.jpg)

But in Sublime the color is different, and a little more complicated to distinguish

![sublime-blade](https://cloud.githubusercontent.com/assets/8865334/23878459/44358404-0826-11e7-858f-17fb315ab1f9.jpg)

Is there any way to change the color to look like Atom? I've seen that the TwoDark.tmTheme file mentions the #C678DD color for blade tags and @ but it doesen't seems to work.

**Comment by erremauro** [comment]
Hi and thank you for your feedback. 

TwoDark include [one-dark-sublime-text-3-color-scheme](https://github.com/IceTimux/one-dark-sublime-text-3-color-scheme) created by [IceTimux](https://github.com/IceTimux) as a syntax color scheme but unfortunately is not actively maintained anymore. 

I'll look into that and see if it can be fixed.

**Comment by elvis-pereira** [comment]
I started using Sublime a little while so I'm still trying to understand how things work, but if I can find something or can help in some other way you can count on me
